---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                .*\.ref$|
                .*\.svg$|
                build/|
                dist/|
                src/actinia_core.egg-info/
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
                .*\.ref$|
                .*\.svg$|
                build/|
                dist/|
                src/actinia_core.egg-info/
          )
  - repo: https://github.com/mundialis/github-workflows
    rev: 1.4.1
    hooks:
    - id: linting

